import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/* ✅ 여기 head 추가 */}
      <head>
        <Script
          async
          strategy="afterInteractive"
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3230635014319056"
          crossOrigin="anonymous"
        />
      </head>

      <body>
        <header style={{ background: '#fff', borderBottom: '1px solid #e5e7eb', marginBottom: '20px' }}>
          <div style={{ maxWidth: '800px', margin: '0 auto', padding: '15px 10px' }}>
             <h1 style={{ fontSize: '18px', fontWeight: 'bold', color: '#16a34a' }}>비급여 가격비교</h1>
          </div>
        </header>


        {/* 모든 페이지 콘텐츠가 이 800px 박스 안에 담깁니다 */}
        <main style={{ maxWidth: '800px', margin: '0 auto', padding: '0 10px 40px' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
